### ISSUE TITLE
Show all buttons by default

### ISSUE THREAD

**Issue by vlstill** [matejos/ISMU-Automata-Editor#2]
Could you please modify the graph editor to show all buttons by default? I think they are needed in most cases.

**Comment by matejos** [comment]
Sure

**Comment by matejos** [comment]
How exactly would you like it? Should I remove the "Další ovládací prvky" button completely or just have those additional buttons shown by default?

By the way, I'm not sure if you know this, but they are additional because their actions can be done with mouse (doubleclick) for the first two or hitting delete on keyboard for the third (state deletion). So I would say, in most cases they aren't needed, because in most cases you should be on a computer with a mouse, no? 😄
